// WITH THIS METHOD WE PREVENT SOME VARIABLE OCCASSIONALY DUPLICATE...ALL MUST BE DISTINCT FROM EACH OTHER



export const HIDE_NEAREST = 'HIDE_NEAREST'

export const SET_FIRST_SELECT = 'SET_FIRST_SELECT'
export const SET_SECOND_SELECT = 'SET_SECOND_SELECT'

export const SET_MAIN_MARKER = 'CHANGE_MAIN_MARKER'
export const REFRESH_MAIN_MARKER = 'REFRESH_MAIN_MARKER'

export const SET_SECONDARY_MARKER = 'SET_SECONDARY_MARKER'


// FETCH NEAREST SHOPS TO POINTER ( PART OF FIRST QUERY)
export const FETCH_SHOPS = 'FETCH_SHOPS'
export const FETCH_SHOPS_SUCC = 'FETCH_SHOPS_SUCC'
export const FETCH_SHOPS_ERR = 'FETCH_SHOPS_ERR' 

// FETCH NEAREST AMENITIES TO POINTER ( PART OF FIRST QUERY)
export const FETCH_AMENITIES = 'FETCH_AMENITIES'
export const FETCH_AMENITIES_SUCC = 'FETCH_AMENITIES_SUCC'
export const FETCH_AMENITIES_ERR = 'FETCH_AMENITIES_ERR'

// FETCH NEAREST STOPS TO POINTER (THIS IS SECOND QUERY)
export const FETCH_NEAREST_STOPS = 'FETCH_NEAREST_STOPS'
export const FETCH_NEAREST_STOPS_SUCC = 'FETCH_NEAREST_STOPS_SUCC'
export const FETCH_NEAREST_STOPS_ERR = 'FETCH_NEAREST_STOPS_ERR'


export const FETCH_NEAREST_CONNECTION = 'FETCH_NEAREST_CONNECTION'
export const FETCH_NEAREST_CONNECTION_SUCC = 'FETCH_NEAREST_CONNECTION_SUCC'
export const FETCH_NEAREST_CONNECTION_ERR = 'FETCH_NEAREST_CONNECTION_ERR'




// RANGE VALUE
export const SET_RANGE_VALUE = 'SET_RANGE_VALUE'
